### ISSUE TITLE
TODO's post clinic

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/2021-Cloud-Hackathon#51]
Just a few ideas as followup for @virdi from the Clinic

- consider having them create their own repo in their GitHub account so they'll have push access
- reorder the "git clone" step to be before step 3

**Comment by jules32** [comment]
I can help, and @betolink too :)

**Comment by virdi** [comment]
creating a very detailed, beginner-friendly, step-by-step git setup section to be followed along by just copy/paste and clicking on links

**Comment by virdi** [comment]
The clinic section looks good, we can create another issue if we need further enhancements
