### ISSUE TITLE
Add License info to this repo?

### ISSUE THREAD

**Issue by fperez** [NASA-Openscapes/2021-Cloud-Hackathon#98]
Great work on this repo, thanks so much! We'd like to use some of the code in here for a tutorial in a few weeks for an ICESat-2 science team workshop, where @tsnow03 and I will be discussing the [new 2i2c-hosted hub for the IS-2/cryo community](https://cryointhecloud.com/). But I don't see  a license in this repo... Without an explicit license, code is by default (in the US at least) copyright to the author with all rights reserved, so I can't really use it until a license is put on the repo.

Our content will all be BSD/MIT-licensed (with CC-BY for non-code), it would be awesome if your license choice could be compatible, but that's obviously your call.

Thanks!

**Comment by jules32** [comment]
Hi @fperez thank you for this Issue and glad the repo is useful! Excited that you'll be reusing it. 

I've just added a MIT LICENSE file to our repo (modeled from your https://github.com/CryoInTheCloud/CryoCloudWebsite/blob/main/LICENSE). And this is a good spark to make sure all our work has the appropriate license and citation. Thank you, and good luck with the ICESat-2 workshop!

**Comment by fperez** [comment]
Wonderful, many thanks @jules32!! Amazing work on openscapes, btw :) 🚀

**Comment by jules32** [comment]
Thanks @fperez , and you as well, in so many open science places!! 🚀 ❤️
